name: Tests

on:
  pull_request:
  push:
    # trying and staging branches are for BORS config
    branches:
      - trying
      - staging
      - main
env:
  IMAGE_NAME: meilisearch_aws_ci_test_$(date +'%d-%m-%Y-%H-%M-%S')

jobs:
  tests:
    # Will not run if the event is a PR to bump-meilisearch-v* (so a pre-release PR)
    # Will still run for each push to bump-meilisearch-v*
    if: github.event_name != 'pull_request' || !startsWith(github.base_ref, 'bump-meilisearch-v')
    name: build-image-test
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: pip3 install -r requirements.txt
    - name: Set image name as env variable
      run: |
        echo "IMAGE_NAME=meilisearch_aws_ci_test_$(date +'%d-%m-%Y-%H-%M-%S')"
        echo "IMAGE_NAME=meilisearch_aws_ci_test_$(date +'%d-%m-%Y-%H-%M-%S')" >> $GITHUB_ENV
        echo $GITHUB_ENV
    - name: Build image
      run: python3 tools/build_image.py ${{ env.IMAGE_NAME }} --no-analytics
    - name: Test image
      run: python3 tools/test_image.py ${{ env.IMAGE_NAME }}
    - name: Clean image
      if: ${{ always() }}
      run: python3 tools/destroy_image.py ${{ env.IMAGE_NAME }}

  pylint:
    name: pylint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: pip3 install -r requirements.txt
      - name: Linter with pylint
        run: pylint tools
